Added SDK client generation template
pagopa/azure-pipeline-templates pull request #11
Opened 2021-01-28 09:42 UTC by gquadrati

Added new template for auto-generation of client SDK based on the OpenAPI spec of the project.

2021-01-28 10:48 UTC, balanza requested changes
Very good! The overall work is well done and very valuable.

Besides a couple of suggestions on docs, I think we should have this template executed at least on a case, to prove it's solid and can be committed into this collection.

2021-01-28 10:48 UTC, balanza commented on templates/client-sdk-release/README.md
> +Opinionated sequence of steps to generate the client SDK wiith models based on an OpenAPI spec. It does the following:
It's not actually a sequence of step, it's an entire stage. We should be explicit on that

2021-01-28 10:48 UTC, balanza commented on templates/client-sdk-release/README.md
> +Be sure that this template is called **after** the main package.json as been updated.
Besides the typo:
```suggestion
Be sure that this template is called **after** the main package.json has been updated.
```

I think I understand the meaning: you are assuming this template would be executed in a context on which you are bumping the version of some other application. 
Anyway, I find this period a bit confusing for someone who's not as aware as we are of the ideas behind this template. 

Maybe we can refer `@pagopa/openapi-codegen-ts`'s documentation for implementation detail, or provide some use real-world example as use case (those are just options, don't read them as requests).

2021-01-29 23:24 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +           displayName: 'Generate client and definitions'
Use `workingDirectory` to declare the folder you want to run the script on

2021-01-29 23:24 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +           displayName: 'Install depencencies'
see above

2021-01-29 23:24 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +           displayName: 'Build depencencies'
see above

2021-01-29 23:24 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +stages:
As the stage contains only one job, is it really worth the effort to include the stage declaration in the template?
By doing this we are hiding information to the consumer pipeline.

2021-01-29 23:24 UTC, balanza commented on .devops/baseTemplateTest/deploy-base-template.yml
> +# Azure DevOps Base pipeline to release a new version of 'io-funtions-xyz' and deploy to production.
I didn't understand how this file is used

2021-01-31 13:04 UTC, gquadrati commented on .devops/baseTemplateTest/deploy-base-template.yml
> +# Azure DevOps Base pipeline to release a new version of 'io-funtions-xyz' and deploy to production.
> I didn't understand how this file is used

The usage is to extend it in each deploy pipeline and use to guide the whole deployment process. 
Good thing is that in this way we will anymore need to change each deploy pipeline of each "io-functions-xyz" project, but only this file, like we should do now for adding the new sdk package generation step.
You can see an example of how we should use it in [deploy-pipeline-extends-base-pipeline.yml](https://github.com/pagopa/azure-pipeline-templates/pull/11/files/d02d5b047e7ef1b586fad6d97c059fe47fe772dd#diff-e52c9898eadbba95dfe6f865cfed00a846fe68e390333980e23f245ced5ca445)
This is all the code we need in every project.

This was just for testing , I should move it to another PR I known, sorry  about that.

2021-01-31 13:14 UTC, gquadrati commented on templates/client-sdk-release/template.yaml
> +stages:
> As the stage contains only one job, is it really worth the effort to include the stage declaration in the template?
> By doing this we are hiding information to the consumer pipeline.

Using a template it always mean hide information to the consumer. In this way I considered the possibility to add more stages in future, if necessary. 
But I can remove it if it's not necessary.

2021-01-31 13:18 UTC, gquadrati commented on templates/client-sdk-release/template.yaml
> +           displayName: 'Generate client and definitions'
is [this](https://github.com/pagopa/azure-pipeline-templates/blob/master/templates/node-job-setup/template.yaml#L41) working? how did you manage to make it work?

2021-02-01 17:08 UTC, gquadrati commented on templates/client-sdk-release/template.yaml
> +stages:
I need to test it again because of the variables I set in the stage, but ok... I'll remove it

2021-02-04 15:14 UTC, balanza commented on .devops/test-pipelines.yaml
> +          workingDirectory: .devops/__tests__/client-sdk-generation/test-sdk/client_src
EOF

2021-02-04 15:14 UTC, balanza commented on .gitignore
> +generated_sdk/
EOF

2021-02-04 15:14 UTC, balanza commented on README.md
> +* [Autogenerated Client SDK Release](templates/client-sdk-release)
Let's talk about the template name: the word "release" is already used in this collection, and it refers to the act of mark a new version of something. Actually, the current template uses an already-done release to pack a SDK and publish on the registry; we should mark the difference. 

Proposals:
* api-sdk-publish
* client-sdk-publish

2021-02-04 15:14 UTC, balanza commented on templates/client-sdk-release/README.md
> +A collection of one or more stages to generate the client SDK wiith models based on an OpenAPI spec. It does the following:
```suggestion
A sequence of steps to generate and publish a SDK package based on a given OpenAPI spec. It does the following:
```

2021-02-04 15:14 UTC, balanza commented on templates/client-sdk-release/README.md
> +1. publish the package to NPM
```suggestion
1. publish the package to NPM

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/README.md
> +     openapiSpecPath: openapi/index.yaml
```suggestion
 - stage: Publish_SDK
    jobs:
      - job: do_generate_and_publish
         steps: 
	     - template: templates/client-sdk-release/template.yaml@templates 
                parameters:
                openapiSpecPath: openapi/index.yaml
```

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +    default: []
I think this is no longer needed
```suggestion
```

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +  - name: 'projectDir'
should we rename this `apiProjectDir`?

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +#   displayName: 'Copy bundle files'
do we need them or not?

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +    default: ''
Proposal:
we can set the npm registry as default, so we don't have to bother if we are in test env or not
```suggestion
    default: 'https://registry.npmjs.org/'
```

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +    default: false
Apply this if we decide to use the npm registry as default for `npmRegistry`

```suggestion
````

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +    echo "##vso[task.setvariable variable=setNpmRegistryValue;]$NPM_REGISTRY"
Apply this if we decide to use the npm registry as default for npmRegistry
```suggestion
```

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/template.yaml
> +    customCommand: publish --access public $(setNpmRegistryValue)
Apply this if we decide to use the npm registry as default for npmRegistry
```suggestion
    customCommand: publish --access public --registry $(npmRegistry)
```

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/README.md
> +|dependsOn|The of the stage that performs the versioning ||no|
I think we don't need this anymore
```suggestion
```

2021-02-04 15:45 UTC, balanza commented on templates/client-sdk-release/README.md
> +|projectDir|The project directory, in case of multi-project repo |.|no!
Add other parameters
```suggestion
|projectDir|The project directory, in case of multi-project repo |`.`|no|
|npmRegistry|Use this to publish on a registry different than the NPM official. We also use this to publish on an ephemeral Verdaccio registry during tests |`https://registry.npmjs.org/`|no|
| artifactName |The name of the artifact that the job will publish, containing the package final bundle to publish from|`Bundle_SDK`|no|

```

2021-02-04 17:55 UTC, gquadrati commented on README.md
> +* [Autogenerated Client SDK Release](templates/client-sdk-release)
I prefer client-sdk-publish

2021-02-04 18:12 UTC, gquadrati commented on templates/client-sdk-release/template.yaml
> +    default: ''
Fine for me

2021-02-04 18:27 UTC, balanza commented on templates/client-sdk-publish/README.md
> +|sdkPackageName|The name of the generated package| _Inherited from the project's package.json_ |no|
```suggestion
	|sdkPackageName|The name of the generated package| _Inherited from the api project's package.json_ |no|
```

2021-02-04 18:27 UTC, balanza commented on templates/client-sdk-publish/template.yaml
> +    customCommand: publish --access public --registry ${{ parameters.npmRegistry }}
👍

2021-02-04 18:28 UTC, gquadrati commented on templates/client-sdk-publish/template.yaml
> +    customCommand: publish --access public --registry ${{ parameters.npmRegistry }}
thanks to the tests!  👍 👍 👍

2021-02-04 18:37 UTC, balanza submitted a review, later dismissed
LGTM. Great job, thank you!

2021-02-04 18:38 UTC, balanza commented on .devops/__tests__/client-sdk-generation/test-sdk/api_src/.gitignore
> +nohup.out
```suggestion

```

2021-02-04 18:38 UTC, gquadrati commented on .devops/__tests__/client-sdk-generation/test-sdk/api_src/.gitignore
> +nohup.out
ouch!!

2021-02-04 18:43 UTC, balanza approved these changes

2021-02-04 18:43 UTC, merged