[#176591264] Yarn lockfile upgrade template
pagopa/azure-pipeline-templates pull request #20
Opened 2021-02-11 11:23 UTC by gquadrati

This PR adds a new template for allowing a project to frequently update its dependencies.

- [x] Created template for upgrading yarn.lock file and making a PR against the GitHub Repo
- [x]  Created a test for testing the template
- [ ]  Add a GITHUB_TOKEN (secret) GITHUB_USERNAME and GITHUB_EMAIL
- [ ] hadle older PR open

2021-02-15 15:18 UTC, balanza requested changes
That seems great, very good. There is something we'd better change, but it looks good overall.

About bash scripting: when the script has more than one instruction, please write `set -euo pipefail` at the beginning of the scripts: that would improve error handling and ensure the whole script interrupts as soon as one instruction fails.

2021-02-15 15:18 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +      #if there is a PR already open, close it
can't we just update the same PR? Also, to check PR title is weak, as we can manually edit such. The best would be to check the branch name

2021-02-15 15:18 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +      fi
instead of this check, we can have a parameter like `baseBranch` which we can set to `master` as default. Apart being more clean, it could be useful when dealing with repos with different branch naming or strategy (think about `main` of `develop` branches).

2021-02-15 15:18 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +          hub pull-request -m "$title" -m "$description" $(hub_pr_cmd)
I didn't see when we installed `hub`

2021-02-15 15:18 UTC, balanza commented on .devops/test-pipelines.yaml
> +      condition: and(succeeded(), not( contains(variables['System.PullRequest.SourceBranch'], 'lockfile-auto-upgrade-') ))
We can define which branch we want to exclude in the trigger configuration https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers

2021-02-15 15:18 UTC, balanza commented on .devops/test-pipelines.yaml
> +    condition: and(succeeded(), not( contains(variables['System.PullRequest.SourceBranch'], 'lockfile-auto-upgrade-') ))
ditto

2021-02-15 15:18 UTC, balanza commented on .devops/test-pipelines.yaml
> +      - job: do_yarn_lock_upgrade_test_1
Can you be more descriptive on the kind fo test we're going to execute?

2021-02-15 15:40 UTC, gquadrati commented
> That seems great, very good. There is something we'd better change, but it looks good overall.

Thanks :)

> About bash scripting: when the script has more than one instruction, please write `set -euo pipefail` at the beginning of the scripts: that would improve error handling and ensure the whole script interrupts as soon as one instruction fails.

About the `set -euo pipefail` command... actually I added it, but I experienced a big problem with the line `PULL_REQUEST_NUMBER=$(hub pr list | grep "\[Yarn.lock Upgrade]" | awk '{print $1}' | sed 's/#//')`
Any suggestion?

2021-02-15 15:41 UTC, balanza commented
What kind of problem?

2021-02-15 15:44 UTC, gquadrati commented on templates/yarn-lock-upgrade/README.md
> +Be sure that this template is called intoyarn a shceduled pipeline
> Besides typos, I'm not sure why this statement is needed. The template itself make no difference if it's being called from a scheduled or manual pipeline



> What kind of problem?

It makes this command crash (and so the whole job).. it took me quite some time to understand that that line was the problem

2021-02-15 15:45 UTC, gquadrati commented
> What kind of problem?

It makes this command crash (and so the whole job).. it took me quite some time to understand that that line was the problem

2021-02-15 15:51 UTC, balanza commented
> > What kind of problem?
> 
> It makes this command crash (and so the whole job).. it took me quite some time to understand that that line was the problem

I the script failed, it was because one of its instructions did. You removed `set -euo pipefail` and suddenly everything works, but it's not so: you still have a failing instructions, you just ignoring it.

2021-02-15 15:53 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +        oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
> Can we move this is a dedicated step?

Since _[hub]()_  is a command line tool that wraps git, I thought to group it into Git setup script, but sure we can have a different script

2021-02-15 15:57 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +      #if there is a PR already open, close it
> can't we just update the same PR? 

I did it in the first place, then I realized that master can evolve and we could have problems with dependencies. 
Plus, in this way we will close useless PR in case the update has been applied to master branch to someone else.
What do you think?

> Also, to check PR title is weak, as we can manually edit such. The best would be to check the branch name

Right, I'll do like this

2021-02-15 16:01 UTC, gquadrati commented
> > > What kind of problem?
> > 
> > 
> > It makes this command crash (and so the whole job).. it took me quite some time to understand that that line was the problem
> 
> I the script failed, it was because one of its instructions did. You removed `set -euo pipefail` and suddenly everything works, but it's not so: you still have a failing instructions, you just ignoring it.

You're right, I this that the problem is that not always `hub pr list` returns a list containing `[Yarn.lock Upgrade]`, so `grep` crashes.. I'll try to handle the case somehow, any suggestions?

2021-02-15 16:02 UTC, gquadrati commented on templates/yarn-lock-upgrade/README.md
> +Be sure that this template is called intoyarn a shceduled pipeline
Removed in [a9712b8](https://github.com/pagopa/azure-pipeline-templates/pull/20/commits/a9712b811ade697c08d14ee82a3d34ab8fec40c5)

2021-02-15 16:10 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +        oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
It actually makes no difference for the end result. While logically I agree with you, maybe having it in a separated step would make an eventual failure easier to debug. But it's only a matter of style, you choose.

2021-02-15 16:13 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +      #if there is a PR already open, close it
> we could have problems with dependencies

The easier solution would be to use `push --force` to be sure to have only latest changes.

My biggest concerns is I'm afraid we will end up flooded by closed PRs, but if it's too much of work we can consider this an improve and eventually do it in next iterations.

2021-02-15 16:18 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +      #if there is a PR already open, close it
> > we could have problems with dependencies
> 
> The easier solution would be to use `push --force` to be sure to have only latest changes.
> 
> My biggest concerns is I'm afraid we will end up flooded by closed PRs, but if it's too much of work we can consider this an improve and eventually do it in next iterations.

Not, I did it, I just need to find that code or re-write it.. You're absolutely right about it

2021-02-15 16:20 UTC, balanza commented
> > > > What kind of problem?
> > > 
> > > 
> > > It makes this command crash (and so the whole job).. it took me quite some time to understand that that line was the problem
> > 
> > 
> > I the script failed, it was because one of its instructions did. You removed `set -euo pipefail` and suddenly everything works, but it's not so: you still have a failing instructions, you just ignoring it.
> 
> You're right, I this that the problem is that not always `hub pr list` returns a list containing `[Yarn.lock Upgrade]`, so `grep` crashes.. I'll try to handle the case somehow, any suggestions?

Try
```sh
set -euo pipefail
$X = $(myCommand | grep "my string" || echo "my default string")
echo "$X";
```

2021-02-15 16:56 UTC, gquadrati commented
> > > > > What kind of problem?
> > > > 
> > > > 
> > > > It makes this command crash (and so the whole job).. it took me quite some time to understand that that line was the problem
> > > 
> > > 
> > > I the script failed, it was because one of its instructions did. You removed `set -euo pipefail` and suddenly everything works, but it's not so: you still have a failing instructions, you just ignoring it.
> > 
> > 
> > You're right, I this that the problem is that not always `hub pr list` returns a list containing `[Yarn.lock Upgrade]`, so `grep` crashes.. I'll try to handle the case somehow, any suggestions?
> 
> Try
> 
> ```shell
> set -euo pipefail
> $X = $(myCommand | grep "my string" || echo "my default string")
> echo "$X";
> ```

Thanks, it seems it's working fine in commit [c902c51](https://github.com/pagopa/azure-pipeline-templates/pull/20/commits/c902c5105881ea437aa45f62f41abad1b0bf42f0)

2021-02-15 16:59 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +      #if there is a PR already open, close it
Retrieving PR number from branch name is working fine in commit [c902c51](https://github.com/pagopa/azure-pipeline-templates/pull/20/commits/c902c5105881ea437aa45f62f41abad1b0bf42f0)

2021-02-15 17:06 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +      fi
Added `baseBranch` parameter in [2a432d5](https://github.com/pagopa/azure-pipeline-templates/pull/20/commits/c902c5105881ea437aa45f62f41abad1b0bf42f0)

But please, consider that we can remove the 'isTest' condition once we merge this PR into master.

2021-02-15 17:07 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +          hub pull-request -m "$title" -m "$description" $(hub_pr_cmd)
> I didn't see when we installed `hub`

We don't! It's already installed :D I was skeptic too

2021-02-15 17:08 UTC, gquadrati commented on .devops/test-pipelines.yaml
> +      condition: and(succeeded(), not( contains(variables['System.PullRequest.SourceBranch'], 'lockfile-auto-upgrade-') ))
I tried without success... I'm gonna make some other trial

2021-02-15 18:26 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +      #if there is a PR already open, close it
Re-used same PR in commit [d5f90bb](https://github.com/pagopa/azure-pipeline-templates/pull/20/commits/d5f90bb8d40ac308c150f4442d8583c5607f5caf)

2021-02-15 18:30 UTC, gquadrati commented on .devops/test-pipelines.yaml
> +
@balanza I tried with this condition, but it doesn't work

2021-02-16 08:44 UTC, balanza requested changes

2021-02-16 08:44 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +        git merge origin/${{ parameters.baseBranch }}
This instruction is critical as it can fail due to conflicts. Maybe we can mitigate by using an explicit [merge strategy](https://git-scm.com/docs/git-merge#Documentation/git-merge.txt--Xltoptiongt):
```suggestion
        git checkout $CURRENT_BRANCH
        git merge -X theirs origin/${{ parameters.baseBranch }}
```
Once conflicts are solved, there's no need to `push --force`, as the history will be linear.

Another option is to _override_ the current branch and start over from master
```suggestion
        git checkout master
        git branch -D $CURRENT_BRANCH
        git checkout -b $CURRENT_BRANCH
```
This will ensure a clean slate for our changes, but it will require to `push --force` later.

2021-02-16 08:44 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +          fi
This should be done **before** make the actual changes (yarn install). I see it's working anyway, as changes don't impede branch switch, but there may be edge cases for which that's not true.

2021-02-16 08:49 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +          fi
Since it's just a modified file, I did this way for not creating a new branch if it's not needed (in case there are no changes).
But since we don't push it, I can do this way sure

2021-02-16 10:18 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +          fi
Done in [e39b9a8](https://github.com/pagopa/azure-pipeline-templates/pull/20/commits/e39b9a8ec0186e12f17eeb4e1b5e9562f4a66535)

2021-02-16 10:51 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +        branch_name="$branch_prefix-$(date +%s)"
Do we still need dates? As we are now using the same branch, I think we don't need it anymore. What do you think?

The script will be easier because `branch_name`, `branch_prefix` and `CURRENT_BRANCH` will be basically the same thing

2021-02-16 11:05 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +        branch_name="$branch_prefix-$(date +%s)"
can we use the same branch multiple times even if it is merged?

2021-02-16 11:13 UTC, gquadrati commented on templates/yarn-lock-upgrade/template.yaml
> +        branch_name="$branch_prefix-$(date +%s)"
Actuially I don't like the idea of making a PR from an already merged branch. 
Do you think is necessary to change it, since I've already implemented the unique branch management?

2021-02-16 11:23 UTC, balanza commented on templates/yarn-lock-upgrade/template.yaml
> +        branch_name="$branch_prefix-$(date +%s)"
ok, that's fine

2021-02-16 11:31 UTC, balanza requested changes

2021-02-16 11:31 UTC, balanza commented on .devops/test-pipelines.yaml
> +
I think you should not use both include and exclude:

> If you specify an exclude clause without an include clause, then it is equivalent to specifying * in the include clause.

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers

2021-02-16 11:31 UTC, balanza commented on .devops/test-pipelines.yaml
> +
Also, I think it does not work this way. If you want to use a wildcard, you should use `*`. Try

```yaml
pr:
  branches:
    exclude:
    - lockfile-auto-upgrade-*
```

2021-02-16 11:40 UTC, gquadrati commented on .devops/test-pipelines.yaml
> +
It doesn't work

2021-02-16 12:09 UTC, balanza approved these changes

2021-02-16 12:17 UTC, merged