[#175934270] Add checks on rest response
pagopa/azure-pipeline-templates pull request #4
Opened 2020-12-01 11:03 UTC by pasqualedevita

this PR add checks on rest response and also fix an issue when `headers` param is empty

2020-12-01 11:29 UTC, gunzip approved these changes

2020-12-01 13:15 UTC, balanza requested changes

2020-12-01 13:15 UTC, balanza commented on templates/rest-healthcheck/template.yaml
> +          fi
I think this solution is too opinionated. It implies that the healthcheck endpoint responds with a specific payload scheme. This might not be the case if we intend this template to be used by different applications.

Can't we control status code to be 200?

2020-12-02 11:33 UTC, pasqualedevita commented on templates/rest-healthcheck/template.yaml
> +          fi
200 it's an implicit previous implementation check, i.e. container instance output status code
Maybe we can check `app-name` or `version` without specific parameters

```
{
  "name": "app-name",
  "version": "1.0.0"
}
```

```
if [[ ${OUTPUT_REST} == *app-name* ]]; then
  echo "appName: '${{ parameters.appName }}' found, continue"
  exit 0
else
  echo "appName: '${{ parameters.appName }}' not found, fail"
  exit 1
fi
```

2020-12-02 12:43 UTC, balanza commented on templates/rest-healthcheck/template.yaml
> +          fi
The problem we had is this script didn't catch timeout or empty responses. If we could just add such check, it would be more than fine. 
If we can't, maybe we can abstract a bit the template by returning `OUTPUT_REST` and let the calling job to perform a more specific check, if required.

2020-12-02 13:09 UTC, pasqualedevita commented on templates/rest-healthcheck/template.yaml
> +          fi
> The problem we had is this script didn't catch timeout or empty responses. If we could just add such check, it would be more than fine.
```bash
if [[ ${OUTPUT_REST} == *name* ]]; then #or version
```
This will check rest response body that for private endpoints it's inside container log and for public endpoints it's `az rest` command output.
In case of timeout or empty responses script fails the pipeline step because `OUTPUT_REST` is empty or not contains the string `name` (or `version`)

> If we can't, maybe we can abstract a bit the template by returning OUTPUT_REST and let the calling job to perform a more specific check, if required.

No healthcheck must be atomic and self contained.

> I think this solution is too opinionated. It implies that the healthcheck endpoint responds with a specific payload scheme. This might not be the case if we intend this template to be used by different applications.

We can add another parameter `responseCheck` with default value to `name` (or `version`)

2020-12-02 13:30 UTC, balanza commented on templates/rest-healthcheck/template.yaml
> +          fi
> No healthcheck must be atomic and self contained.
Why this hard statement? I mean, this step would always check for the minimum constraint to be satisfied (200 OK), by returning a value we can let the user decide to apply further checks (which would not happen if the basic healthcheck fails).

> We can add another parameter responseCheck with default value to name (or version)

That would be providing a string to look for? Fine. But can't we just check for non-emptyness?

2020-12-02 16:43 UTC, pasqualedevita commented on templates/rest-healthcheck/template.yaml
> +          fi
> That would be providing a string to look for? Fine. But can't we just check for non-emptyness?

2020-12-03 07:50 UTC, balanza approved these changes

2020-12-03 07:50 UTC, merged