[#IO-28] Install azurerm custom provider
pagopa/azure-pipeline-templates pull request #71
Opened 2021-03-10 15:43 UTC by uolter

2021-03-10 16:00 UTC, balanza requested changes
In order to have the template included in our library, it must come with:
* an own README file explaining purpose, usages and parameters
* a reference in the root README file
* at least a test case in the test pipeline, if applicable (the point is to have the template executed and avoid cheap errors like typos and misplaced things)

2021-03-10 16:14 UTC, uolter commented on templates/terraform-custom-azurerm/template.yaml
> +    script: |
it's not gonna work on windows.... I release just one binary built  for linux amd64. Golang behave like C ... is not interpreted :-)

2021-03-10 16:14 UTC, uolter commented on templates/terraform-custom-azurerm/template.yaml
> +  condition: and(ne('${{ parameters.AZURERM_PROVIDER_CUSTOM_VERSION }}', 'none'), ne('${{ parameters.AZURERM_PROVIDER_CUSTOM_RELEASE }}', 'none'))
yep... do you know if I can overwrite them later on .... ?

2021-03-10 16:50 UTC, uolter commented on templates/terraform-custom-azurerm/template.yaml
> +      export TERRAFORM_CACHE_DIR='.terraform.d/plugin-cache/registry.terraform.io/hashicorp/azurerm/${{ parameters.AZURERM_PROVIDER_CUSTOM_VERSION }}/linux_amd64'
this is not a good idea since the wget command writes the download progression in the standard error.
see...
```
    0K .......... .......... .......... .......... ..........  0%  842K 3m45s
    50K .......... .......... .......... .......... ..........  0%  387K 5m56s
   100K .......... .......... .......... .......... ..........  0% 1,80M 4m32s
   150K .......... .......... .......... .......... ..........  0%  628K 4m39s
   200K .......... .......... .......... .......... ..........  0% 4,03M 3m52s
   250K .......... .......... .......... .......... ..........  0%  585K 4m7s
   300K .......... .......... .......... .......... ..........  0%  358K 4m47s
   350K .......... .......... .......... .......... ..........  0%  489K 4m59s

   600K .......... .......... .......... .......... ..........  0%  290K 6m39s
```

2021-03-10 18:16 UTC, pasqualedevita commented on templates/terraform-custom-azurerm/template.yaml
> +      wget https://github.com/uolter/terraform-provider-azurerm/releases/download/${{ parameters.AZURERM_PROVIDER_CUSTOM_RELEASE }}/terraform-provider-azurerm
we can also add a third parameter `AZURERM_PROVIDER_CUSTOM_URL`

2021-03-10 19:33 UTC, balanza commented on templates/terraform-custom-azurerm/template.yaml
> +  - name: 'AZURERM_PROVIDER_CUSTOM_VERSION'
A note on code style (although we codified nothing about it):
prefer using `lowerCamelCase` for local parameters so that it's easier to differentiate from global variables, which we usually encode as `UPPER_SNAKE_CASE`.

So I'd rather use `azurermProviderCustomVersion` instead of `AZURERM_PROVIDER_CUSTOM_VERSION`.

2021-03-11 14:56 UTC, pasqualedevita commented on templates/terraform-custom-azurerm/template.yaml
> +      export TERRAFORM_CACHE_DIR='.terraform.d/plugin-cache/registry.terraform.io/hashicorp/azurerm/${{ parameters.AZURERM_PROVIDER_CUSTOM_VERSION }}/linux_amd64'
see my suggestion above

2021-03-11 14:58 UTC, pasqualedevita commented on templates/terraform-custom-azurerm/README.md
> +* AZURERM_PROVIDER_CUSTOM_RELEASE the release of the custom provider.
```suggestion
* AZURERM_PROVIDER_CUSTOM_RELEASE the release of the custom provider.
* AZURERM_PROVIDER_CUSTOM_URL the url repository from which to download the binary of the custom provider (optional).
```

2021-03-11 16:08 UTC, pasqualedevita approved these changes

2021-03-15 08:53 UTC, merged