Maven Github Release template
pagopa/azure-pipeline-templates pull request #91
Opened 2022-07-22 14:37 UTC by jacopocarlini

### List of changes
- added a template to mark a new release of a Maven project  hosted on a Github repository
- added `prerelease` as a valid value for the parameter  of `node-github-release` template

### Motivation and context

to avoid duplication in the other repository

### Type of changes

- [x] Add new template
- [x] Update template configuration
- [ ] Remove template
- [ ] Other changes

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-07-22 14:58 UTC, balanza requested changes
Besides comments I left, some general considerations:
* consider write tests for the newly introduced template
* add a link into root README.md

2022-07-22 14:58 UTC, balanza commented on templates/node-github-release/template.yaml
> +  - skip
What's skip? If you need to skip the stage, I'd rather:
* use Azure DevOps interface, or
* define a dedicated parameter for the template

2022-07-22 14:58 UTC, balanza commented on templates/node-github-release/template.yaml
> +  default: main
I have no strong opinion on `main` vs `master` debate, anyway lots of pipelines are currently relying on having `master` as default. This would be an annoying breaking change for them.

2022-07-22 14:58 UTC, balanza commented on templates/node-github-release/README.md
> +1. bump the version according to a given [SemVer](https://semver.org/) option (`major`, `minor`, `patch` or `prerelease`)
Advice for next time: keep unrelated changes on dedicated PRs. Changes on `node-github-release` are not related to `maven-github-release`, are they?

2022-07-22 14:58 UTC, balanza commented on templates/maven-github-release/template.yaml
> +          options: '-DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-${parsedVersion.nextBuildNumber}'
It seems to me those cases are the very same but some defaults on semver parts. 

Maybe we can apply conditions to `option` field only? Will it improve readability? 

```yaml
      - task: Maven@3
        displayName: 'Bump version'
        inputs:
          mavenPomFile: "pom.xml"
          goals: 'build-helper:parse-version versions:set'
          - ${{ if eq(parameters.semver, 'major') }}:
            options: ' on major...  '
          - ${{ if eq(parameters.semver, 'buildNumber') }}:
            options: ' on build number...  '
```

2022-07-22 15:29 UTC, jacopocarlini commented on templates/node-github-release/template.yaml
> +  default: main
reverted

2022-07-22 15:31 UTC, jacopocarlini commented on templates/node-github-release/template.yaml
> +  - skip
`skip` option removed

2022-07-22 15:31 UTC, jacopocarlini commented on templates/node-github-release/README.md
> +1. bump the version according to a given [SemVer](https://semver.org/) option (`major`, `minor`, `patch` or `prerelease`)
you'r right

2022-07-22 16:05 UTC, jacopocarlini commented on templates/maven-github-release/template.yaml
> +          options: '-DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-${parsedVersion.nextBuildNumber}'
👍

2022-07-22 16:48 UTC, jacopocarlini commented
> Besides comments I left, some general considerations:
> 
> * consider write tests for the newly introduced template
> * add a link into root README.md

Testing this template is hard because:
- it creates a new commit in this repo. 
- it expects the pom file in the root directory of the project

_Note: also `node-github-release` template has no tests_

2022-07-22 17:30 UTC, balanza submitted a review, later dismissed

2022-07-27 11:48 UTC, pasqualedevita requested changes
I suggest to use a standard name on the task that export the next version.
In this way we can reuse the variable in next stages, for example to set docker image version

2022-07-27 11:48 UTC, pasqualedevita commented on templates/maven-github-release/template.yaml
> +    name: pomversion
```suggestion
    name: next_version
```

2022-07-27 11:48 UTC, pasqualedevita commented on templates/maven-github-release/template.yaml
> +        echo "##vso[task.setvariable variable=next;isOutput=true]$version"
```suggestion
        echo "##vso[task.setvariable variable=value;isOutput=true]$version"
```

2022-07-27 11:48 UTC, pasqualedevita commented on templates/maven-github-release/template.yaml
> +      TITLE="Release $(pomversion.next)"
```suggestion
      TAG="$(next_version.value)"
      TITLE="Release $(next_version.value)"
```

2022-07-27 12:21 UTC, pasqualedevita commented
merged in feature branch

2022-07-27 12:21 UTC, merged